-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text not null,
  descr text not null,
  web_url text not null,
  rating INTEGER not null
    check(rating > 0 and rating <= 5)
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, descr, web_url, rating)
values
  ('Google', 'a search engine', 'www.google.com', 5),
  ('Facebook', 'a social networking site', 'www.facebook.com', 2),
  ('LinkedIn', 'a professional networking site', 'www.linkedin.com', 4),
  ('Thinkful', 'a coding bootcamp', 'wwww.thinkful.com', 5),
  ('YouTube', 'a great place to waste time', 'www.youtube.com', 5),
  ('4chan', 'the worst place on the internet', 'www.4chan.org', 1),
  ('GitHub', 'a remote git repository', 'www.github.com', 3),
  ('Free Code Camp', 'a place to learn coding', 'www.freecodecamp.org', 4),
  ('Code Wars', 'a placee to test your coding skills', 'www.codewars.com', 4),
  ('Twitter', 'the presidents soap box', 'www.twitter.com', 1);